name: Test and Build

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  unit_tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn
      - run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn
      - run: yarn build
